### ISSUE TITLE
[Help]为什么无法接受discord邀请，显示邀请失败

### ISSUE THREAD

**Issue by ZhangQing-codebase** [Bkebi-Group/Bkebi-GC-Release#17]
question：
Why can't I join discord。Show unable to join

**Comment by Gktwo** [comment]
你倒是发个图啊，光打字怎么知道

**Comment by ZhangQing-codebase** [comment]
![Screenshot_20230306_112109_com.discord.jpg](https://user-images.githubusercontent.com/127062372/223012537-2c83cc31-654c-4110-8d7d-fe8e92ea8a54.jpg)

**Comment by ZhangQing-codebase** [comment]
加入discord就是这样

**Comment by Gktwo** [comment]
哦，那就是暂停邀请了，现在人多处理不过来

**Comment by ZhangQing-codebase** [comment]
那什么时候重新开放
