### ISSUE TITLE
[Help] key

### ISSUE THREAD

**Issue by whykilx** [Bkebi-Group/Bkebi-GC-Release#22]
Downloaded the latest version of the cheat but there is no key from txt BKEBI-ISFREE-NOT4SALE
I tried to find the answer in the discord server, but I forbade entry there.

[Error] [main.cpp              :226  ] License is invalid! Please make sure you have a valid key!
[Error] [main.cpp              :279  ] Reason: Unknown, please contact support.

![image](https://user-images.githubusercontent.com/126210949/224768448-7ebdf00d-4351-41ed-adc5-d9bebc0a45ca.png)

**Comment by DSGFSDGS7HGJ** [comment]
什么原因

**Comment by Devaaldo** [comment]
join bkebi member first. For further information, check the announcement bkebi.

**Comment by Devaaldo** [comment]
> 
> > join bkebi member first. For further information, check the announcement bkebi.
> 
> I would love to join the discord server, but they have restricted entry into it.
> 

The server invitation will be opened on the 15th and 30th of each month, just wait it.

**Comment by whykilx** [comment]
> > > join bkebi member first. For further information, check the announcement bkebi.
> > 
> > 
> > I would love to join the discord server, but they have restricted entry into it.
> 
> The server invitation will be opened on the 15th and 30th of each month, just wait it.

Unexpectedly, thank you for the information
