### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by snoparata** [Bkebi-Group/Bkebi-GC-Release#7]
**首先, 请绝对确保你使用的 Bkebi是最新版本, 且的确遇到了一个 Bug ，而不是你自己的问题！如果不能确定，请不要使用此模板！**
**First, make absolutely sure that you are using the latest version of Bkebi, and that you are indeed experiencing a bug and not your own problem! If you are not sure, do not use this template!**

## Bug Description / 问题描述

Please enter a clear and accurate description of this bug here.
请在此填入对此 Bug 清晰准确的描述。

## How to Reproduce the Bug / 如何复现问题

Steps to reproduce this bug:
复现此 Bug 的具体步骤: 

1. xx
2. xxxx
3. 

## Screenshot/Video / 截图/录像

If possible, please attach a screenshot or video of the problem here. You can use Ctrl + V to paste the picture directly. Be careful not to disclose your account information. 
如果条件允许，请在此附上问题截图或录像。您可以使用 Ctrl + V 直接粘贴图片。注意不要泄露你的账号信息. 

## Device Information / 设备信息

Provide information about your device, for example: 
提供你的设备信息, 例如: 

 - Operate System information / 操作系统版本 :`Windows 10 家庭中文版-21H1-19043.1949`
 - Bkebi Version / Bkebi 版本 :`1.0.1`
 - Game Version / 游戏版本 : `CN/OS`
 - Other Valued Info / 其他有价值的信息 : 

## Expectation / 期望

Give a brief description of what you expect.
对您所期望的情况做一个简单描述。

## Additional Information / 补充信息

You can enter additional information about this bug here.
您可以在这里输入其他有关此 Bug 的信息。

**Comment by TomyJan** [comment]
?
