### ISSUE TITLE
[Help]按“~”键不能呼出菜单

### ISSUE THREAD

**Issue by DukeWO3o** [Bkebi-Group/Bkebi-GC-Release#8]
## Describe the Problem / 问题描述
为啥进游戏面板没有自动弹出来，按“~”键也没反应。功能能生效，但是面板打不开。我是按照教程一步步来的。

## How to Reproduce the Problem / 如何复现问题
管理员模式开injector.exe，进游戏功能直接生效了，但是菜单打不开。

## Screenshot/Video / 截图/录像
无法打开菜单，截不到图

## Device Information / 设备信息
 - Operate System information / 操作系统版本 :`Windows 11 专业版-22H2-22621.1343`
 - Bkebi Version / Bkebi 版本 :`1.0.3`
 - Game Version / 游戏版本 : `OS`
 - Other Valued Info / 其他有价值的信息 : 

## Help You Need / 你需要的帮助
请告诉我如何正常打开面板。

**Comment by qian1314521** [comment]
应该是f1吧

**Comment by DukeWO3o** [comment]
> 应该是f1吧

不行，也不知道什么原因

**Comment by TomyJan** [comment]
请查看你自己的设置, 确保使用的是正确的按键, Bkebi 的默认热键是 F1 
另外请不要运行微星小飞机等 OSD 软件

**Comment by DukeWO3o** [comment]
解决了！把小飞机、英伟达、xbox的游戏内覆盖全关就行。
